### ISSUE TITLE
Cannot start after upgrade to 2022.7

### ISSUE THREAD

**Issue by EvertJob** [speleolontra/daikin_residential_altherma#60]
After upgrading to 2022.7 I've gotten the following error:

``Setup failed for custom integration daikin_residential_altherma: Unable to import component: cannot import name 'Mapping' from 'collections' ``

Am I the only one with this error?

**Comment by jwillemsen** [comment]
Very likely #59 will fix this

**Comment by colseven** [comment]
same here, how can i update the oic?

**Comment by MichalDoom** [comment]
Hello
can you please describe how to upgrade to 1.4.0?i have the same problem.
thank You

**Comment by colseven** [comment]
edit this file: /config/custom_components/daikin_residential_altherma/manifest.json
change Line 12 to      "oic==1.4.0"

**Comment by jwillemsen** [comment]
See https://github.com/speleolontra/daikin_residential_altherma/pull/59/files for the exact change

**Comment by MichalDoom** [comment]
done and works again.Thanks

**Comment by gerard76** [comment]
Same! 👍
